@port = 5000
@baseurl = http://localhost:{{port}}/api/v1
@bookEp ={{baseurl}}/book

#Create a Book
###
POST {{bookEp}}/createBook
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJpYXQiOjE3NDA3MDgwMzAsImV4cCI6MTc0MDc5NDQzMH0.2E5qlbZ5xXik7lrR0ZZPn6X8BBRC-dghO8FLTDwqj9A

{
  "status": "inactive",
  "title": "The book book",
  "author": "The Author",
  "isbn": "9780786",
  "publishedYear": 1925,
  "thumbnail": "https://bookimg.com/thumbnail.jpg",
  "description": "A Book",
  "isAvailable": true,
  "averageRating": 4.5
}


# Get all Books (Admin)
###
GET {{bookEp}}/adminGetBooks
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJpYXQiOjE3NDA3MDgwMzAsImV4cCI6MTc0MDc5NDQzMH0.2E5qlbZ5xXik7lrR0ZZPn6X8BBRC-dghO8FLTDwqj9A

# Get all Books (public)
###
GET {{bookEp}}/publicGetBooks

#Update a Book
###
PUT {{bookEp}}/updateBook
Content-Type:application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJpYXQiOjE3NDA3MDgwMzAsImV4cCI6MTc0MDc5NDQzMH0.2E5qlbZ5xXik7lrR0ZZPn6X8BBRC-dghO8FLTDwqj9A
 
{
      "_id": "67bbcc6572031b68f14c01a6",
      "status": "inactive",
      "title": "book",
      "author": "book writer",
      "genre": "autobiography",
      "isbn": "12370456",
      "publishedYear": 2020,
      "thumbnail": "https://wallpapercave.com/wp/rdYAno5.jpg",
      "description": "helloo",
      "isAvailable": true,
      "expectedAvailable": null
    
      
    }

# Delete a Book
###
DELETE {{bookEp}}/deleteBook/67bd4147ba4f86de48043c01
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJpYXQiOjE3NDA3MDgwMzAsImV4cCI6MTc0MDc5NDQzMH0.2E5qlbZ5xXik7lrR0ZZPn6X8BBRC-dghO8FLTDwqj9b

