@port = 5000
@baseurl = http://localhost:{{port}}/api/v1
@bookEp ={{baseurl}}/book

#Create a Book
###
POST {{bookEp}}/createBook
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJpYXQiOjE3NDE2MDU3MTQsImV4cCI6MTc0MTY5MjExNH0.O_U3FsF_pat5APQB2LipjrpR5gSAhqG1X17zHLVoQwI

{
  "status": "active",
  "title": "The Hitchhiker's Guide to the Galaxy",
  "author": "Douglas Adams",
  "genre": "fiction",
  "isbn": "978-0345391803",
  "publishedYear": 1979,
  "thumbnail": "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
  "description": "A comedic science fiction series created by Douglas Adams that has become a popular culture phenomenon.",
  "isAvailable": true,
  "isFeatured": true
}



# Get all Books (Admin)
###
GET {{bookEp}}/adminGetBooks
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJpYXQiOjE3NDE2NDYzNTEsImV4cCI6MTc0MTczMjc1MX0.RBbcnJQP14OgCTq6x0wl9eCWYq1xrAfMPcp0ojU1FKw


# Get Featured Books
###
GET {{bookEp}}/featuredBooks


# Get all Books (public)
###
GET {{bookEp}}/publicGetBooks

#Update a Book
###
PUT {{bookEp}}/updateBook
Content-Type:application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJpYXQiOjE3NDE2NDYzNTEsImV4cCI6MTc0MTczMjc1MX0.RBbcnJQP14OgCTq6x0wl9eCWYq1xrAfMPcp0ojU1FKw
 
{
  "_id": "67cf80702da998511e4e810c",
  "thumbnail": "https://as1.ftcdn.net/v2/jpg/04/32/30/30/1000_F_432303031_ysOUhColEZEl8eSZkSUOFNqOiN1W6x2u.jpg"
  }

# Delete a Book
###
DELETE {{bookEp}}/deleteBook/67bcecbb21a5a85aa2c3be2a
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJpYXQiOjE3NDE2MDU3MTQsImV4cCI6MTc0MTY5MjExNH0.O_U3FsF_pat5APQB2LipjrpR5gSAhqG1X17zHLVoQwI
