@port = 5000
@baseurl = http://localhost:{{port}}/api/v1
@authEP = {{baseurl}}/auth

#Signup
POST {{authEP}}/signup
Content-Type: application/json

{
  "fName": "Bob",
  "lName": "Marley",
  "email": "bob@gmail.com",
  "password": "password",
  "phone": "1234567890",
  "role": "admin"
}

#Login
###
POST {{authEP}}/login
Content-Type: application/json

{
  "email" : "bob@gmail.com",
  "password" : "password"
}


#Renew JWT
###
GET {{authEP}}/renewJWT
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvYkBnbWFpbC5jb20iLCJpYXQiOjE3NDA0NTU4NzYsImV4cCI6MTc0MTc1MTg3Nn0.jRGWXXB1XuXq0AyWetFoz4DRevjB-34p9oeUXffi-4A